import os
import json
from datetime import datetime
from pathlib import Path

COMPANION_DIR = Path(__file__).parent.parent / "tmp" / "companion"
COMPANION_DIR.mkdir(parents=True, exist_ok=True)

PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="{description}">
<meta name="keywords" content="{keywords}">
<meta name="author" content="Vyom Ai Cloud">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{description}">
<meta property="og:image" content="{thumbnail_url}">
<meta property="og:type" content="video.other">
<title>{title} &mdash; Vyom Ai Cloud</title>
<style>
*{{margin:0;padding:0;box-sizing:border-box}}
body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Oxygen,Ubuntu,sans-serif;background:#0a0a0f;color:#e0e0e0;line-height:1.6}}
.container{{max-width:900px;margin:0 auto;padding:20px}}
.video-wrapper{{position:relative;padding-bottom:56.25%;height:0;overflow:hidden;border-radius:12px;margin-bottom:24px}}
.video-wrapper iframe{{position:absolute;top:0;left:0;width:100%;height:100%;border:none}}
h1{{font-size:1.8rem;margin-bottom:8px;color:#fff}}
.meta{{color:#888;font-size:0.9rem;margin-bottom:20px}}
.meta span{{margin-right:16px}}
.badge{{display:inline-block;padding:3px 10px;border-radius:4px;font-size:0.8rem;margin-right:6px;margin-bottom:6px}}
.badge-cat{{background:#6366f1;color:#fff}}
.badge-tag{{background:#1e1e2e;color:#22d3ee;border:1px solid #22d3ee33}}
.section{{margin-bottom:28px}}
.section h2{{font-size:1.2rem;color:#6366f1;margin-bottom:12px;border-bottom:1px solid #1e1e2e;padding-bottom:6px}}
.description{{color:#bbb;white-space:pre-wrap}}
.chapter{{display:flex;align-items:center;padding:8px 12px;background:#14141f;border-radius:6px;margin-bottom:6px}}
.chapter-time{{color:#6366f1;font-family:monospace;min-width:50px}}
.chapter-title{{color:#ddd}}
.thumb{{max-width:100%;border-radius:8px;margin-bottom:16px}}
.footer{{border-top:1px solid #1e1e2e;padding-top:16px;margin-top:32px;color:#555;font-size:0.8rem;text-align:center}}
.footer a{{color:#6366f1;text-decoration:none}}
</style>
</head>
<body>
<div class="container">
<img class="thumb" src="{thumbnail_url}" alt="{title}">
<h1>{title}</h1>
<div class="meta">
<span>&#x1F4F9; {format}</span>
<span>&#x1F4C5; {date}</span>
<span>&#x1F517; <a href="{video_url}" style="color:#6366f1;text-decoration:none">Watch on YouTube</a></span>
</div>
<div>
<span class="badge badge-cat">{category}</span>
{tag_badges}
</div>
<div class="video-wrapper">
<iframe src="https://www.youtube.com/embed/{video_id}" allow="accelerometer;autoplay;clipboard-write;encrypted-media;gyroscope;picture-in-picture" allowfullscreen></iframe>
</div>
<div class="section">
<h2>Description</h2>
<div class="description">{description}</div>
</div>
{chapters_section}
{disclaimer_section}
</div>
<div class="footer">
<p>Generated by <a href="https://vyomai.cloud">Vyom Ai Cloud</a> &mdash; AI-powered educational content</p>
<p>Published {date}</p>
</div>
</body>
</html>"""

DISCLAIMER_HTML = """
<div class="section">
<h2>Disclaimer</h2>
<div class="description" style="font-size:0.85rem;color:#888">
This content was created with the assistance of artificial intelligence.
While we strive for accuracy, some information may contain errors or
omissions. Always verify critical technical details from primary sources.
</div>
</div>"""


def _format_date(dt_str: str) -> str:
    try:
        dt = datetime.fromisoformat(dt_str)
        return dt.strftime("%B %d, %Y")
    except Exception:
        return datetime.utcnow().strftime("%B %d, %Y")


def _build_chapters_html(chapters: list[dict]) -> str:
    if not chapters:
        return ""
    lines = ['<div class="section">', "<h2>Chapters</h2>"]
    for ch in chapters:
        start = ch.get("start_time", 0)
        mins = int(start // 60)
        secs = int(start % 60)
        title = ch.get("title", "Chapter")
        lines.append(
            f'<div class="chapter">'
            f'<span class="chapter-time">{mins}:{secs:02d}</span>'
            f'<span class="chapter-title">{title}</span>'
            f"</div>"
        )
    lines.append("</div>")
    return "\n".join(lines)


def _build_tag_badges(tags: list[str]) -> str:
    if not tags:
        return ""
    return "".join(f'<span class="badge badge-tag">{t}</span>' for t in tags if t.strip())


def generate_companion_page(
    video_id: str,
    title: str,
    description: str,
    category: str,
    tags: list[str],
    thumbnail_url: str,
    video_url: str,
    format_type: str = "long",
    chapters: list[dict] = None,
    include_disclaimer: bool = True,
    publish_date: str = None,
) -> str:
    output_path = str(COMPANION_DIR / f"{video_id}.html")
    tag_badges = _build_tag_badges(tags or [])
    chapters_html = _build_chapters_html(chapters or [])
    disclaimer_html = DISCLAIMER_HTML if include_disclaimer else ""
    date_str = _format_date(publish_date) if publish_date else datetime.utcnow().strftime("%B %d, %Y")
    fmt_label = "Short Video" if format_type == "shorts" else "Long Form"
    escaped_title = title.replace("&", "&amp;").replace('"', "&quot;").replace("<", "&lt;").replace(">", "&gt;")
    escaped_desc = (description or "No description provided.").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    keywords = ", ".join(tags[:10]) if tags else category

    html = PAGE_TEMPLATE.format(
        title=escaped_title,
        description=escaped_desc,
        keywords=keywords,
        thumbnail_url=thumbnail_url,
        video_url=video_url,
        video_id=video_id,
        format=fmt_label,
        date=date_str,
        category=category,
        tag_badges=tag_badges,
        chapters_section=chapters_html,
        disclaimer_section=disclaimer_html,
    )

    try:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)
        print(f"[COMPANION] Generated companion page: {output_path} ({os.path.getsize(output_path)} bytes)")
        return output_path
    except Exception as e:
        print(f"[COMPANION] Failed to write companion page: {e}")
        return ""


def upload_companion_page(file_path: str, video_id: str) -> str:
    try:
        from utils.r2_storage import get_r2_client, BUCKET, ACCOUNT_ID
        client = get_r2_client()
        key = f"companion/{video_id}/index.html"
        with open(file_path, "rb") as f:
            client.upload_fileobj(
                f,
                BUCKET,
                key,
                ExtraArgs={
                    "ContentType": "text/html; charset=utf-8",
                    "Metadata": {
                        "uploaded-at": datetime.utcnow().isoformat(),
                        "video-id": video_id,
                    },
                },
            )
        public_url = f"https://pub-{ACCOUNT_ID}.r2.dev/{key}"
        print(f"[COMPANION] Uploaded to R2: {key} -> {public_url}")
        return public_url
    except Exception as e:
        print(f"[COMPANION] Failed to upload to R2: {e}")
        return ""
